language: python

sudo: required

services:
        - docker

python:
        - 2.7
        - 3.5

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y numactl liblapacke-dev


install: 
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install .

script:
        - python -m pytest
